# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Youth_Read(中青自动阅读)

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 * * * *'
  watch:
    types: Youth_Read
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ5 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ6 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ6 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ7 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ8 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ9 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ10 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ11 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ12 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ13 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ14 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ15 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ16 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ17 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ18 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ19 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ20 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ21 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ5
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ5 }}
